---
- hosts: vm
  roles:
    - swap

- hosts: all
  gather_facts: no
  roles:
    - { role: apt_proxy, when: use_apt_proxy }
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

- hosts: postgresql
  roles:
    - postgresql

- hosts: elasticsearch
  become: yes
  become_user: root
  roles:
    - { role: geerlingguy.elasticsearch }

- hosts: application
  handlers:
    - include: roles/sidekiq/handlers/main.yml
  roles:
    - base
    - { role: ruby, tags: ruby }
    - vim
    - webserver

- hosts: sidekiq
  handlers:
    - include: roles/puma/handlers/main.yml
  roles:
    - base
    - ruby
    - { role: geerlingguy.redis }
    - { role: sidekiq, tags: sidekiq }

- hosts: application
  handlers:
    - include: roles/sidekiq/handlers/main.yml
  roles:
    - base
    - { role: ruby, tags: ruby }
    - vim
    - webserver
